# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: pip install -r requirements.txt 
    name: Test Case for Login User
    command: pytest -v -m tcid04

  - before: pip install -r requirements.txt
    name: Test Case for Create User in Terminal 2
    command: pytest -v -m tcid05